os: add missing header for BSDs after fd4be8b9ca93 (#16)
src/os/Process.cpp:105:9: error: use of undeclared identifier 'sigemptyset'
  105 |         sigemptyset(&set);
      |         ^
src/os/Process.cpp:106:21: error: use of undeclared identifier 'SIG_SETMASK'
  106 |         sigprocmask(SIG_SETMASK, &set, NULL);
      |                     ^